# This workflow scrapes, parses, and uploads data to MongoDB on a daily basis

name: Daily update

on:
  workflow_dispatch:
  schedule:
    - cron: '10 1 * * *'
  pull_request: # temporary until merged

jobs:

  astra:
    runs-on: ubuntu-latest
    steps:

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Fill env for dev
      run: |
        cp .env.template .env
        sed -i 's#LOGIN_ASTRA_USERNAME=#LOGIN_ASTRA_USERNAME=${{ secrets.LOGIN_ASTRA_USERNAME }}#' .env
        sed -i 's#LOGIN_ASTRA_PASSWORD=#LOGIN_ASTRA_PASSWORD=${{ secrets.LOGIN_ASTRA_PASSWORD }}#' .env
        sed -i 's#MAZEVO_API_KEY=#MAZEVO_API_KEY=${{ secrets.MAZEVO_API_KEY }}#' .env
        sed -i 's#MONGODB_URI=#MONGODB_URI=${{ secrets.MONGODB_URI_DEV }}#' .env

    - name: Setup
      run: make setup

    - name: Check
      run: make check

    - name: Build
      run: make build

    - name: Scrape Astra
      env:
        CHROME_BIN: /usr/bin/google-chrome
      run: |
        xvfb-run --auto-servernum ./api-tools -scrape -astra

#    - name: Parse Astra
#      run: ./api-tools -parse -astra

#    - name: Upload Astra
#      run: ./api-tools -upload -events

    - name: Fill env for prod
      run: |
        cp .env.template .env
        sed -i 's#LOGIN_ASTRA_USERNAME=#LOGIN_ASTRA_USERNAME=${{ secrets.LOGIN_ASTRA_USERNAME }}#' .env
        sed -i 's#LOGIN_ASTRA_PASSWORD=#LOGIN_ASTRA_PASSWORD=${{ secrets.LOGIN_ASTRA_PASSWORD }}#' .env
        sed -i 's#MAZEVO_API_KEY=#MAZEVO_API_KEY=${{ secrets.MAZEVO_API_KEY }}#' .env
        sed -i 's#MONGODB_URI=#MONGODB_URI=${{ secrets.MONGODB_URI_PROD }}#' .env

#    - name: Upload Astra
#      run: ./api-tools -upload -events

  mazevo:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Fill env for dev
      run: |
        cp .env.template .env
        sed -i 's#LOGIN_ASTRA_USERNAME=#LOGIN_ASTRA_USERNAME=${{ secrets.LOGIN_ASTRA_USERNAME }}#' .env
        sed -i 's#LOGIN_ASTRA_PASSWORD=#LOGIN_ASTRA_PASSWORD=${{ secrets.LOGIN_ASTRA_PASSWORD }}#' .env
        sed -i 's#MAZEVO_API_KEY=#MAZEVO_API_KEY=${{ secrets.MAZEVO_API_KEY }}#' .env
        sed -i 's#MONGODB_URI=#MONGODB_URI=${{ secrets.MONGODB_URI_DEV }}#' .env

    - name: Setup
      run: make setup

    - name: Check
      run: make check

    - name: Build
      run: make build

    - name: Scrape Mazevo
      run: ./api-tools -scrape -mazevo

#    - name: Parse Mazevo
#      run: ./api-tools -parse -mazevo

#    - name: Upload Mazevo
#      run: ./api-tools -upload -events

    - name: Fill env for prod
      run: |
        cp .env.template .env
        sed -i 's#LOGIN_ASTRA_USERNAME=#LOGIN_ASTRA_USERNAME=${{ secrets.LOGIN_ASTRA_USERNAME }}#' .env
        sed -i 's#LOGIN_ASTRA_PASSWORD=#LOGIN_ASTRA_PASSWORD=${{ secrets.LOGIN_ASTRA_PASSWORD }}#' .env
        sed -i 's#MAZEVO_API_KEY=#MAZEVO_API_KEY=${{ secrets.MAZEVO_API_KEY }}#' .env
        sed -i 's#MONGODB_URI=#MONGODB_URI=${{ secrets.MONGODB_URI_PROD }}#' .env

#    - name: Upload Mazevo
#      run: ./api-tools -upload -events
