# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: develop
  pull_request:
    branches: develop
  workflow_dispatch:

jobs:

  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Setup
      run: make setup

    - name: Check
      run: make check

    - name: Test
      env:
        LOGIN_NETID: ${{ secrets.LOGIN_NETID }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      run: make test

    - name: Build
      run: make build

  build_windows:
    runs-on: windows-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Setup
      run: .\build.bat setup

    - name: Check
      run: .\build.bat check

    - name: Test
      env:
        LOGIN_NETID: ${{ secrets.LOGIN_NETID }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      run: .\build.bat test

    - name: Build
      run: .\build.bat build
